In [1]:
import sklearn

In [2]:
import numpy as np


In [3]:
myarr=np.array([[3,6,7,8,9]],np.int64)

In [4]:
myarr

array([[3, 6, 7, 8, 9]], dtype=int64)

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1]=32
myarr

array([[ 3, 32,  7,  8,  9]], dtype=int64)

# Array creation from other python structures

In [8]:
listArray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [9]:
listArray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listArray.dtype


dtype('int32')

In [11]:
listArray.shape

(3, 3)

In [12]:
listArray.size

9

In [13]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.07]])
print("Initial Array")
print(arr)

#Array with first 2 rows and alternate columns (0 and 2)
sliced_arr=arr[:2, ::2]
print(sliced_arr)

Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), (1, 2), (0, 1), (3, 0):\n", Index_arr)

Initial Array
[[-1.    2.    0.    4.  ]
 [ 4.   -0.5   6.    0.  ]
 [ 2.6   0.    7.    8.  ]
 [ 3.   -7.    4.    2.07]]
[[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [14]:
np.array({34,23,23})

array({34, 23}, dtype=object)

# INTRINSIC NUMPY ARRAY CREATION OBJECTS

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
zeros.size

10

**ARANGE

In [20]:
rng=np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
rng.dtype

dtype('int32')

In [23]:
rng.shape

(15,)

In [24]:
rng.size


15

In [25]:
lspace=np.linspace(1,10,6)

In [26]:
lspace

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [27]:
lspace=np.linspace(1,4,4)

In [28]:
lspace

array([1., 2., 3., 4.])

In [29]:
emp=np.empty((2,5))

In [30]:
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
emp=np.empty((2,5))

In [32]:
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
emp.dtype

dtype('float64')

In [34]:
emp.shape

(2, 5)

In [35]:
emp.size

10

In [36]:
emp_like=np.empty_like(lspace)

In [37]:
emp_like

array([1., 2., 3., 4.])

In [38]:
id=np.identity(45)

In [39]:
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
id.shape

(45, 45)

In [41]:
id.size

2025

In [42]:
arr=np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [45]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr=arr.shape

In [47]:
arr

(99,)

In [48]:

x=[[1,4,3],[2,5,8],[7,6,9]]
ar=np.array(x)
ar

array([[1, 4, 3],
       [2, 5, 8],
       [7, 6, 9]])

In [49]:
#sum along different axes//
sum=ar.sum(axis=0)
sum

array([10, 15, 20])

In [50]:
sum=ar.sum(axis=1)
sum

array([ 8, 15, 22])

In [51]:
ar.T

array([[1, 2, 7],
       [4, 5, 6],
       [3, 8, 9]])

In [52]:
for item in ar.flat:
    print(item)

1
4
3
2
5
8
7
6
9


In [53]:
ar.ndim

2

In [54]:
ar.size

9

In [55]:
ar.nbytes

36

In [56]:
one=np.array([1,3,4,63,4])
one.argmax()

3

In [57]:
one.argmin()

0

In [58]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [59]:
ar

array([[1, 4, 3],
       [2, 5, 8],
       [7, 6, 9]])

In [60]:
ar.argmin()

0

In [61]:
ar.argmax()

8

In [62]:
ar.argsort()

array([[0, 2, 1],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [63]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [64]:
ar.argmax(axis=1)

array([1, 2, 2], dtype=int64)

In [65]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [66]:
ar.argmin(axis=1)

array([0, 0, 1], dtype=int64)

In [67]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [68]:
ar.argsort(axis=1)

array([[0, 2, 1],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [69]:
ar.ravel

<function ndarray.ravel>

In [70]:
ar.ravel()

array([1, 4, 3, 2, 5, 8, 7, 6, 9])

In [71]:
ar.reshape((9,1))

array([[1],
       [4],
       [3],
       [2],
       [5],
       [8],
       [7],
       [6],
       [9]])

In [73]:
ar.ravel()

array([1, 4, 3, 2, 5, 8, 7, 6, 9])

In [74]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])
ar+ar2

array([[ 2,  6,  4],
       [ 6,  5, 14],
       [15,  7,  9]])

In [75]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [76]:
ar*ar2

array([[ 1,  8,  3],
       [ 8,  0, 48],
       [56,  6,  0]])

In [77]:
np.sqrt(ar)

array([[1.        , 2.        , 1.73205081],
       [1.41421356, 2.23606798, 2.82842712],
       [2.64575131, 2.44948974, 3.        ]])

In [78]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [79]:
ar.sum()

45

In [80]:
ar.max()

9

In [81]:
ar2.max()

8

In [82]:
ar2.min()

0

In [83]:
ar2.sum()

23

In [84]:
arr=np.array([[1,2,3],[4,5,6],[7,1,0]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [85]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [86]:
type(np.where(arr>5))

tuple

In [87]:
np.count_nonzero(arr)

8

In [88]:
np.count_nonzero(ar)

9

In [90]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [91]:
arr[1,2]=0

In [92]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [93]:
import sys

In [95]:
ch_arr=[0,4,5,5,2]
np_array=np.array(ch_arr)
sys.getsizeof(1)*len(np_array)

140

In [96]:
np_array.itemsize*np_array.size

20

In [97]:
np_array.tolist()

[0, 4, 5, 5, 2]